server:
  port: 9999
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.130:8848

  application:
    name: authorization-server
  redis:
    host: 192.168.2.130
    password: Password123!
    database: 0
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.2.130:3307/coin-exchange?useSSL=false&serverTimezon=GMT%28
    username: root
    password: Ltd3411??
    driver-class-name: com.mysql.cj.jdbc.Driver