server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.130:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-server-router
          uri:  https://www.aliyun.com/
          predicates:
            - Path=/product
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
    sentinel:
      datasource:
#        ds1.file:
#          file: classpath:gw-flow.json
#          ruleType: gw-flow
#        ds2.file:
#          file: classpath:api-group.json
#          ruleType: gw_api-group
        ds1.nacos:
          serverAddr: 192.168.2.130:8848
          dataId: gw-flow
          ruleType: gw_flow
        ds2.nacos:
          serverAddr: 192.168.2.130:8848
          dataId: api-group
          ruleType: gw_api-group